import { Manrope } from "next/font/google";
import "./globals.css";
import ThemeProvider from "../components/shared/ThemeProvider";
import NavBar from "@/components/shared/NavBar";

const ManropeFont = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" suppressHydrationWarning
      className={`${ManropeFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <NavBar></NavBar>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
